# Generated by Django 5.1.1 on 2024-09-04 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_doneitems_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doneitems',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.item'),
            preserve_default=False,
        ),
    ]
