# Generated by Django 5.1.1 on 2024-09-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_doneitems_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doneitems',
            name='item',
        ),
        migrations.RemoveField(
            model_name='doneitems',
            name='user',
        ),
    ]
