# Generated by Django 5.1.1 on 2024-09-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_doneitems_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
